name: build

on:
  push:
    branches:
      - master
      - newci
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set GDL Dir
      run: mkdir gdl && cd gdl

    - name: Get GDL
      uses: actions/checkout@v2
      with:
        repository: gnudatalanguage/gdl

    - name: Build GDL
      run: |
        ls
        cd gdl
        sed -i 's/\/\/#define GDL_DEBUG/#define GDL_DEBUG/g' src/dinterpreter.cpp
        scripts/build_gdl.sh prep
        scripts/build_gdl.sh configure
        scripts/build_gdl.sh build
        scripts/build_gdl.sh install

    - name: make
      run: make
