name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build GDL
      run: |
        mkdir gdl
        cd gdl
        git clone https://github.com/gnudatalanguage/gdl
        scripts/build_gdl.sh prep
        scripts/build_gdl.sh configure
        scripts/build_gdl.sh build
        scripts/build_gdl.sh install

    - name: make
      run: make
