name: build

on:
  push:
    branches:
      - master
      - newci
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set GDL Dir
      run: mkdir gdl && cd gdl

    - name: Get GDL
      uses: actions/checkout@v2
      with:
        repository: no-lex/idl2src

    - name: Get GDL
      uses: actions/checkout@v2
      with:
        repository: gnudatalanguage/gdl

    - name: Build GDL
      run: |
        sed -i 's/\/\/#define GDL_DEBUG/#define GDL_DEBUG/g' src/dinterpreter.cpp
        scripts/build_gdl.sh prep
        scripts/build_gdl.sh configure
        scripts/build_gdl.sh build
        scripts/build_gdl.sh install
        cd ..

    - name: Get idl2src
      uses: actions/checkout@v2
      with:
        repository: no-lex/idl2src

    - name: make
      run: make

    - name: Upload binary artifact
      uses: actions/upload-artifact@v2
      with:
        name: idl2src
        path: ./idl2src

    - name: Get FHD
      uses: actions/checkout@v2
      with:
        repository: EoRImaging/FHD

    - name: Make Database
      run: |
        ls
        ls ..
        cp ../idl2src/idl2src idl2src
        cp ../idl2src/run_indexer.sh run_indexer.sh
        cp ../idl2src/ci_script.sh ci_script.sh
